# These are supported funding model platforms
github: [Haris-khan-Durrani]
patreon: Haris-khan-Durrani
tidelift: npm/Mainland-activity-list
custom: # ["https://www.buymeacoffee.com/hariskha",hariskhandurrani.com]
