# These are supported funding model platforms
github: [Haris-khan-Durrani]
[![Buy Me a Coffee](https://img.shields.io/badge/Donate-Buy%20Me%20a%20Coffee-orange.svg)](https://www.buymeacoffee.com/hariskha)
custom: # ["https://www.buymeacoffee.com/hariskha",hariskhandurrani.com]
